#!/bin/sh

if [[ -v SKIP ]]; then
    printf "Skipping ALSA check\n"
    exit 0
fi

if [ ! -d "$BUILD/repos/alsa-lib" ]; then
    git clone https://github.com/alsa-project/alsa-lib "$BUILD/repos/alsa-lib"
fi

cd "$BUILD/repos/alsa-lib"

if [[ -n "$TAG" ]]; then
    git fetch --tags --force --all
    current_tag="$(git describe --exact-match --tags 2>/dev/null || true)"

    if [[ "$current_tag" != "$TAG" ]]; then
        printf "Switching to tag $TAG\n"

        #determine if we're on an undetached branch. if we are, then we need to pull
        if ! (git checkout $TAG 2>&1 | grep -qE '(HEAD is now at|Your branch is up to date)'); then
            git -C "$BUILD/repos/alsa-lib" pull 2>&1
        fi

        REBUILD="alsa"
    fi
fi

if [[ "$CLEAN_BUILD" == "yes" ]] || [[ "$REBUILD" == "alsa" ]] || ! ( git pull 2>&1 | grep -qE '(Already up to date|You are not currently on a branch)' ); then
    "$BUILD/scripts/alsa-build"
else
    printf "Nothing to update for ALSA\n"
fi
