#!/bin/sh

echo() { printf %s\\n "$*"; }  # depends on standard IFS (which we have)

rm -rf "$BUILD/ffmpeg_build"

if test -f "$BUILD"/ffmpeg_options ; then
    OPTIONS=($(xargs < "$BUILD/ffmpeg_options"))
fi

echo "Using ffmpeg options: ${OPTIONS[@]}"

mkdir -p "$BUILD/ffmpeg_build"
cd "$BUILD/ffmpeg_build"

"$BUILD/repos/ffmpeg/configure" --prefix="$BUILD/build_libs" "${OPTIONS[@]}"

cd "$BUILD"
make -C "$BUILD/ffmpeg_build" install -j$(nproc)
