#!/bin/bash

if test -f "$BUILD"/fribidi_options ; then
    OPTIONS=($(xargs < "$BUILD/fribidi_options"))
fi

printf 'Using fribidi options: %s\n' "${OPTIONS[*]}"

cd "$BUILD/repos/fribidi"
rm -rf build

meson setup build -Dbuildtype=release --prefix=$BUILD/build_libs -Ddefault_library=static "${OPTIONS[@]}"
ninja install -C build