#!/bin/sh

newline="
"

if test -f "$BUILD"/fribidi_options ; then
    IFS=$newline
    set -- $(cat "$BUILD"/fribidi_options) "$@"
    unset -v IFS
fi

OPTIONS="--enable-static --disable-shared --without-glib --with-pic"

cd "$BUILD/repos/fribidi"
rm -rf build

meson setup build -Ddocs=false -Dbuildtype=release --prefix=$BUILD/build_libs -Ddefault_library=static
ninja install -C build "$@"

