#!/bin/bash

cd "$BUILD/repos/harfbuzz"

rm -rf build

meson setup build -Dprefer_static=true -Dbuildtype=release --prefix=$BUILD/build_libs -Ddefault_library=static -Dtests=disabled
ninja install -C build
