#!/bin/bash

export PKG_CONFIG_PATH="/usr/lib/pkgconfig:$PKG_CONFIG_PATH"
export PKG_CONFIG_PATH="/usr/lib/x86_64-linux-gnu/pkgconfig:$PKG_CONFIG_PATH"

cd "$BUILD/repos/dovi_tool/dolby_vision"
cargo clean

export RUSTFLAGS="-C target-feature=+crt-static -C link-self-contained=yes"

if ! cargo install --list | grep -q "cargo-c"; then
    echo "cargo-c not found, installing..."
    cargo install cargo-c --target x86_64-unknown-linux-gnu
fi

cargo cinstall --release --prefix $BUILD/build_libs --library-type staticlib