#!/bin/bash

if [[ -v SKIP ]]; then
    printf "Skipping libdisplay-info check\n"
    exit 0
fi

if [ ! -d "$BUILD/repos/libdisplay-info" ]; then
    git clone https://gitlab.freedesktop.org/emersion/libdisplay-info "$BUILD/repos/libdisplay-info"
fi

cd "$BUILD/repos/libdisplay-info"

if [[ -n "$TAG" ]]; then
    git fetch --tags --force --all
    current_tag="$(git describe --exact-match --tags 2>/dev/null || true)"

    if [[ "$current_tag" != "$TAG" ]]; then
        printf "Switching to tag $TAG\n"

        #determine if we're on an undetached branch. if we are, then we need to pull
        if ! (git checkout $TAG 2>&1 | grep -qE '(HEAD is now at|Your branch is up to date)'); then
            git -C "$BUILD/repos/libdisplay-info" pull 2>&1
        fi

        REBUILD="libdisplay-info"
    fi
fi

if [[ "$CLEAN_BUILD" == "yes" ]] || [[ "$REBUILD" == "libdisplay-info" ]] || ! ( git pull 2>&1 | grep -qE '(Already up to date|You are not currently on a branch)' ); then
    "$BUILD/scripts/libdisplay-info-build"
else
    printf "Nothing to update for libdisplay-info\n"
fi
