#!/bin/bash

cd "$BUILD/repos/dovi_tool/dolby_vision"
cargo clean

export RUSTFLAGS="-C target-feature=+crt-static -C link-self-contained=yes"
cargo install cargo-c --target x86_64-unknown-linux-gnu
cargo cinstall --release --prefix $BUILD/build_libs --library-type staticlib