#!/bin/bash

if [[ -v SKIP ]]; then
    printf "Skipping libffi check\n"
    exit 0
fi

if [ ! -d "$BUILD/repos/libffi" ]; then
    git clone https://github.com/libffi/libffi "$BUILD/repos/libffi"
fi

cd "$BUILD/repos/libffi"

if [[ -n "$TAG" ]]; then
    git fetch --tags --force --all
    current_tag="$(git describe --exact-match --tags 2>/dev/null || true)"

    if [[ "$current_tag" != "$TAG" ]]; then
        printf "Switching to tag $TAG\n"

        #determine if we're on an undetached branch. if we are, then we need to pull
        if ! (git checkout $TAG 2>&1 | grep -qE '(HEAD is now at|Your branch is up to date)'); then
            git -C "$BUILD/repos/libffi" pull 2>&1
        fi

        REBUILD="libffi"
    fi
fi

if [[ "$CLEAN_BUILD" == "yes" ]] || [[ "$REBUILD" == "libffi" ]] || ! ( git pull 2>&1 | grep -qE '(Already up to date|You are not currently on a branch)' ); then
    "$BUILD/scripts/libffi-build"
else
    printf "Nothing to update for libffi\n"
fi
