#!/bin/sh

cd "$BUILD/repos/libjpeg"
rm -rf build

cmake -S . -B build -GNinja -DENABLE_SHARED=FALSE -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="$BUILD/build_libs" -DCMAKE_INSTALL_DEFAULT_LIBDIR="lib"
ninja install -C build
