#!/bin/bash

if test -f "$BUILD"/libplacebo_options ; then
    OPTIONS=($(xargs < "$BUILD/libplacebo_options"))
fi

printf 'Using libplacebo options: %s\n' "${OPTIONS[*]}"

cd "$BUILD/repos/libplacebo"
rm -rf build

meson setup build -Dprefer_static=true -Ddefault_library=static -Dprefix="$BUILD/build_libs" "${OPTIONS[@]}"
ninja install -C build