#!/bin/sh

if test -f "$BUILD"/libplacebo_options ; then
    OPTIONS=($(xargs < "$BUILD/libplacebo_options"))
fi

echo "Using libplacebo options: ${OPTIONS[@]}"

cd "$BUILD/repos/libplacebo"
rm -rf build

meson setup build -Dprefer_static=true -Ddefault_library=static -Dprefix="$BUILD/build_libs" "${OPTIONS[@]}"
ninja install -C build