#!/bin/bash

cd "$BUILD/repos/libunibreak"
make distclean

./autogen.sh --prefix=$BUILD/build_libs
./configure --prefix=$BUILD/build_libs --enable-static --disable-shared

make -j$(nproc)
make install