#!/bin/bash

cd "$BUILD/repos/libxkbcommon"
rm -rf build

meson setup build -Dprefer_static=true -Dbuildtype=release -Dprefix=$BUILD/build_libs -Ddefault_library=static -Denable-x11=false -Dc_args='-fPIC' -Dc_link_args='-fPIC'
ninja install -C build
