#!/bin/bash

if [ ! -d "$BUILD/repos/mpv" ]; then
    git clone https://github.com/mpv-player/mpv "$BUILD/repos/mpv"
	CLEAN_BUILD="yes"
fi

cd "$BUILD/repos/mpv"

if [[ -n "$TAG" ]]; then
    git fetch --tags --force --all
    current_tag="$(git describe --exact-match --tags 2>/dev/null || true)"

    if [[ "$current_tag" != "$TAG" ]]; then
        printf "Switching to tag $TAG\n"

        #determine if we're on an undetached branch. if we are, then we need to pull
        if ! (git checkout $TAG 2>&1 | grep -qE '(HEAD is now at|Your branch is up to date)'); then
            git -C "$BUILD/repos/mpv" pull 2>&1
        fi

        REBUILD="mpv"
    fi
fi

if [[ "$CLEAN_BUILD" == "yes" ]] || [[ "$REBUILD" == "mpv" ]] || ! ( git pull 2>&1 | grep -qE '(Already up to date|You are not currently on a branch)' ); then
    "$BUILD/scripts/mpv-build"
else
    printf "Nothing to update for mpv\n"
fi
