#!/bin/sh

newline="
"

export LDFLAGS="-static-libgcc -static-libstdc++"

if test -f "$BUILD"/mpv_options ; then
    OPTIONS=($(xargs < "$BUILD/mpv_options"))
fi

cd "$BUILD/repos/mpv"
rm -rf build

meson setup build -Dprefer_static=true -Dbuildtype=release "${OPTIONS[@]}"
meson compile -C build
