#!/bin/sh

if [[ -v SKIP ]]; then
    printf "Skipping mujs check\n"
    exit 0
fi

if [ ! -d "$BUILD/repos/mujs" ]; then
    git clone https://cgit.ghostscript.com/mujs.git "$BUILD/repos/mujs"
fi

cd "$BUILD/repos/mujs"

if [[ -n "$TAG" ]]; then
    git fetch --tags --force --all
    current_tag="$(git describe --exact-match --tags 2>/dev/null || true)"

    if [[ "$current_tag" != "$TAG" ]]; then
        printf "Switching to tag $TAG\n"

        #determine if we're on an undetached branch. if we are, then we need to pull
        if ! (git checkout $TAG 2>&1 | grep -qE '(HEAD is now at|Your branch is up to date)'); then
            git -C "$BUILD/repos/mujs" pull 2>&1
        fi

        REBUILD="mujs"
    fi
fi

if [[ "$CLEAN_BUILD" == "yes" ]] || [[ "$REBUILD" == "mujs" ]] || ! ( git pull 2>&1 | grep -qE '(Already up to date|You are not currently on a branch)' ); then
    "$BUILD/scripts/mujs-build"
else
    printf "Nothing to update for mujs\n"
fi
