#!/bin/bash

export PKG_CONFIG_PATH="/usr/lib/pkgconfig:$PKG_CONFIG_PATH"
export PKG_CONFIG_LIBDIR="usr/lib/pkgconfig:$PKG_CONFIG_LIBDIR"
export PKG_CONFIG_PATH="/usr/lib/x86_64-linux-gnu/pkgconfig:$PKG_CONFIG_PATH"
export PKG_CONFIG_LIBDIR="usr/lib/x86_64-linux-gnu/pkgconfig:$PKG_CONFIG_LIBDIR"

if test -f "$BUILD"/pipewire_options ; then
    OPTIONS=($(xargs < "$BUILD/pipewire_options"))
fi

printf 'Using pipewire options: %s\n' "${OPTIONS[*]}"

cd "$BUILD/repos/pipewire"
rm -rf builddir

meson setup builddir -Dprefix=$BUILD/build_libs "${OPTIONS[@]}"
ninja install -C builddir

ar rcs libpipewire-0.3.a $(find builddir -name '*.o')
cp libpipewire-0.3.a $BUILD/build_libs/lib/
printf "Stitched together libpipewire-0.3.a and copied it to $BUILD/build_libs/lib/libpipewire-0.3.a\n"
