#!/bin/bash

export PKG_CONFIG_PATH="/usr/lib/pkgconfig:$PKG_CONFIG_PATH"
export PKG_CONFIG_LIBDIR="usr/lib/pkgconfig:$PKG_CONFIG_LIBDIR"
export PKG_CONFIG_PATH="/usr/lib/x86_64-linux-gnu/pkgconfig:$PKG_CONFIG_PATH"
export PKG_CONFIG_LIBDIR="usr/lib/x86_64-linux-gnu/pkgconfig:$PKG_CONFIG_LIBDIR"

if test -f "$BUILD"/pipewire_options ; then
    OPTIONS=($(xargs < "$BUILD/pipewire_options"))
fi

printf 'Using pipewire options: %s\n' "${OPTIONS[*]}"

cd "$BUILD/repos/pipewire"
rm -rf builddir

meson setup builddir -Dprefix=$BUILD/build_libs "${OPTIONS[@]}"
ninja install -C builddir

unset PKG_CONFIG_PATH
export PKG_CONFIG_LIBDIR="$BUILD/build_libs/lib/pkgconfig"
export PKG_CONFIG_LIBDIR="$BUILD/build_libs/share/pkgconfig:$PKG_CONFIG_LIBDIR"
export PKG_CONFIG_LIBDIR="$BUILD/build_libs/lib/x86_64-linux-gnu/pkgconfig:$PKG_CONFIG_LIBDIR"

ar rcs libpipewire-0.3.a $(find builddir -name '*.o')

PIPEWIRE_PATH=$(pkg-config --libs-only-L libpipewire-0.3 | sed 's/^-L//')

cp libpipewire-0.3.a "$PIPEWIRE_PATH"
printf "Stitched together pipewire-0.3.a and copied it to $PIPEWIRE_PATH/libpipewire-0.3.a\n"
