#!/bin/bash

cd "$BUILD/repos/Vulkan-Loader"
rm -rf build

cmake -S . -B build -GNinja -DVULKAN_HEADERS_INSTALL_DIR="$BUILD/build_libs/include/vulkan" -DBUILD_WSI_XCB_SUPPORT=OFF -DBUILD_WSI_XLIB_SUPPORT=OFF -DBUILD_WSI_XLIB_XRANDR_SUPPORT=OFF -DBUILD_SHARED_LIBS=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="$BUILD/build_libs" -DCMAKE_POSITION_INDEPENDENT_CODE=ON
ninja install -C build

ar rcs libvulkan.a $(find build -name '*.o')

VULKAN_PATH=$(pkg-config --libs-only-L vulkan | sed 's/^-L//')

cp libvulkan.a "$VULKAN_PATH"
printf "Stitched together libvulkan.a and copied it to $VULKAN_PATH/libvulkan.a\n"