#!/bin/sh

cd "$BUILD/repos/Vulkan-Headers"
rm -rf build

cmake -S . -B build -GNinja -DVULKAN_HEADERS_ENABLE_TESTS=OFF -DBUILD_SHARED_LIBS=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="$BUILD/build_libs" -DCMAKE_POSITION_INDEPENDENT_CODE=ON
ninja install -C build