#!/bin/bash

if [[ -v SKIP ]]; then
    printf "Skipping Vulkan-Headers check\n"
    exit 0
fi

if [ ! -d "$BUILD/repos/Vulkan-Headers" ]; then
    git clone https://github.com/KhronosGroup/Vulkan-Headers "$BUILD/repos/Vulkan-Headers"
fi

cd "$BUILD/repos/Vulkan-Headers"

if [[ -n "$TAG" ]]; then
    git fetch --tags --force --all
    current_tag="$(git describe --exact-match --tags 2>/dev/null || true)"

    if [[ "$current_tag" != "$TAG" ]]; then
        printf "Switching to tag $TAG\n"

        #determine if we're on an undetached branch. if we are, then we need to pull
        if ! (git checkout $TAG 2>&1 | grep -qE '(HEAD is now at|Your branch is up to date)'); then
            git -C "$BUILD/repos/Vulkan-Headers" pull 2>&1
        fi

        REBUILD="Vulkan-Headers"
    fi
fi

if [[ "$CLEAN_BUILD" == "yes" ]] || [[ "$REBUILD" == "Vulkan-Headers" ]] || ! ( git pull 2>&1 | grep -qE '(Already up to date|You are not currently on a branch)' ); then
    "$BUILD/scripts/vulkan-headers-build"
else
    printf "Nothing to update for Vulkan-Headers\n"
fi