#!/bin/sh

if [[ -v SKIP ]]; then
    printf "Skipping wayland check\n"
    exit 0
fi

if [ ! -d "$BUILD/repos/wayland" ]; then
    git clone https://gitlab.freedesktop.org/wayland/wayland "$BUILD/repos/wayland"
fi

cd "$BUILD/repos/wayland"

if [[ -n "$TAG" ]]; then
    git fetch --tags --force --all
    current_tag="$(git describe --exact-match --tags 2>/dev/null || true)"

    if [[ "$current_tag" != "$TAG" ]]; then
        printf "Switching to tag $TAG\n"

        #determine if we're on an undetached branch. if we are, then we need to pull
        if ! (git checkout $TAG 2>&1 | grep -qE '(HEAD is now at|Your branch is up to date)'); then
            git -C "$BUILD/repos/wayland" pull 2>&1
        fi

        REBUILD="wayland"
    fi
fi

if [[ "$CLEAN_BUILD" == "yes" ]] || [[ "$REBUILD" == "wayland" ]] || ! ( git pull 2>&1 | grep -qE '(Already up to date|You are not currently on a branch)' ); then
    "$BUILD/scripts/wayland-build"
else
    printf "Nothing to update for wayland\n"
fi