#!/bin/sh

cd "$BUILD/repos/xxHash"
rm -rf build_cmake

cmake -S build/cmake/ -B build_cmake -GNinja -DBUILD_SHARED_LIBS=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="$BUILD/build_libs" -DCMAKE_POSITION_INDEPENDENT_CODE=ON
ninja install -C build_cmake