#!/bin/bash

if [[ -v SKIP ]]; then
    printf "Skipping xxHash check\n"
    exit 0
fi

if [ ! -d "$BUILD/repos/xxHash" ]; then
    git clone https://github.com/Cyan4973/xxHash "$BUILD/repos/xxHash"
fi

cd "$BUILD/repos/xxHash"

if [[ -n "$TAG" ]]; then
    git fetch --tags --force --all
    current_tag="$(git describe --exact-match --tags 2>/dev/null || true)"

    if [[ "$current_tag" != "$TAG" ]]; then
        printf "Switching to tag $TAG\n"

        #determine if we're on an undetached branch. if we are, then we need to pull
        if ! (git checkout $TAG 2>&1 | grep -qE '(HEAD is now at|Your branch is up to date)'); then
            git -C "$BUILD/repos/xxHash" pull 2>&1
        fi

        REBUILD="xxHash"
    fi
fi

if [[ "$CLEAN_BUILD" == "yes" ]] || [[ "$REBUILD" == "xxHash" ]] || ! ( git pull 2>&1 | grep -qE '(Already up to date|You are not currently on a branch)' ); then
    "$BUILD/scripts/xxhash-build"
else
    printf "Nothing to update for xxHash\n"
fi